# Generated by Django 3.2 on 2021-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compaies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateField(blank=True, default=None, max_length=255, null=True)),
                ('updated_at', models.DateField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
