# Generated by Django 3.2 on 2021-04-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compaies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateField(blank=True, default=None, max_length=255, null=True)),
                ('updated_at', models.DateField(auto_now=True, max_length=255, null=True)),
                ('app', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='compaies_dev', to='Compaies.compaies')),
            ],
        ),
    ]
