# Generated by Django 3.2 on 2021-04-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compaies', '0001_initial'),
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('created_at', models.DateField(blank=True, default=None, max_length=255, null=True)),
                ('updated_at', models.DateField(auto_now=True, max_length=255, null=True)),
                ('data', models.JSONField(default=dict)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='compaies_loc', to='Compaies.compaies')),
                ('device_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='device_loc', to='Devices.devices')),
            ],
        ),
    ]
